# To point shell to minikube's docker-daemon:
# `eval $(minikube docker-env)`
# To revert:
# `eval $(minikube docker-env --unset)`

rbac:
  enabled: true

controller:
  priorityClassName: system-cluster-critical
  ingressClassName: traefik
  isDefaultIngressClass: true
  image:
    repository: traefik
    tag: "v3.0.0"
    pullPolicy: Always
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
