---
rbac:
  enabled: true

controller:
  enforceTLS: false
  priorityClassName: system-cluster-critical
  ingressClassName: traefik
  isDefaultIngressClass: true
  image:
    repository: traefik
    tag: "v3.5.0"
    pullPolicy: Always
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
