---
version: 2.1

# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.14

# --------------
# Pipeline tasks
# --------------

jobs:

  lint-chart:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/helm-lint-chart

  build-chart:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/helm-build-chart

  deploy:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/terraform-run-plan:
          workspace: noos-prod
          plan-message: ${CIRCLE_BUILD_URL}

# -----------------
# Pipeline workflow
# -----------------

workflows:

  lint-build-deploy:
    jobs:
      - lint-chart
      - hold:
          type: approval
          filters:
            branches:
              only: master
      - build-chart:
          context: CIRCLECI_SHARED
          requires:
            - hold
          filters:
            branches:
              only: master
      - deploy:
          context: NOOS_PROD_SHARED
          requires:
            - build-chart
          filters:
            branches:
              only: master
