---
version: 2.1

default:
  filter: &filter-master-only
    filters:
      branches:
        only: master


# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.1.15


# --------------
# Pipeline tasks
# --------------

jobs:

  lint-chart:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/helm-lint-chart

  build-chart:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/helm-build-chart:
          registry-provider: aws
          chart-name: noos-prod/kube-proxy

  deploy:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/terraform-run-plan:
          workspace: noos-prod
          plan-message: ${CIRCLE_BUILD_URL}


# -----------------
# Pipeline workflow
# -----------------

workflows:

  lint-build-deploy:
    jobs:
      - lint-chart
      - hold:
          type: approval
          <<: *filter-master-only
      - build-chart:
          context: CIRCLECI_SHARED
          requires:
            - hold
          <<: *filter-master-only
      - deploy:
          context: NOOS_PROD_SHARED
          requires:
            - build-chart
          <<: *filter-master-only
