---
version: 2.1

default:
  filter: &filter_master_only
    filters:
      branches:
        only: master


# ----------------
# Orbs declaration
# ----------------

orbs:

  noos-ci: noosenergy/noos-ci@0.2.2


# --------------
# Pipeline tasks
# --------------

jobs:

  lint_chart:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/helm_lint_chart

  build_chart:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/helm_build_chart:
          registry_provider: aws
          chart_name: noos-prod/kube-proxy

  deploy:
    executor: noos-ci/default
    steps:
      - checkout
      - noos-ci/terraform_run_plan:
          workspace: noos-prod
          plan_message: ${CIRCLE_BUILD_URL}


# -----------------
# Pipeline workflow
# -----------------

workflows:

  lint_build_deploy:
    jobs:
      - lint_chart
      - hold:
          type: approval
          <<: *filter_master_only
      - build_chart:
          context: CIRCLECI_SHARED
          requires:
            - hold
          <<: *filter_master_only
      - deploy:
          context: NOOS_PROD_SHARED
          requires:
            - build_chart
          <<: *filter_master_only
