apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClassName }}
  annotations:
    {{- if .Values.controller.isDefaultIngressClass }}
    ingressclass.kubernetes.io/is-default-class: "true"
    {{- end }}
spec:
  controller: traefik.io/ingress-controller
