# v2.8 resources:
#     - Traefik config
#     https://doc.traefik.io/traefik/v2.8/
#     - Helm chart
#     https://github.com/traefik/traefik-helm-chart/tree/master/traefik
#     - CRDs / ingresses
#     https://github.com/traefik/traefik/tree/v2.6/pkg/provider/kubernetes/ingress/fixtures
rbac:
  enabled: true

controller:
  priorityClassName:
  ingressClassName: traefik
  isDefaultIngressClass: true
  image:
    repository: traefik
    tag: "v2.8"
    pullPolicy: Always
  service:
    annotations: {}
  resources: {}
