# v3.7 resources:
#     - Traefik config
#     https://doc.traefik.io/traefik/v3.7/
#     - Helm chart
#     https://github.com/traefik/traefik-helm-chart/tree/master/traefik
#     - CRDs / ingresses
#     https://github.com/traefik/traefik/tree/v3.7/pkg/provider/kubernetes/ingress/fixtures
rbac:
  enabled: false

controller:
  deployTag: latest
  # Whether to enforce TLS by redirecting HTTP to HTTPS
  enforceTLS: false
  # Set Traefik as the cluster default reverse proxy
  ingressClassName: traefik
  isDefaultIngressClass: true
  # Overall deployment
  priorityClassName:
  image:
    repository: traefik
    tag: "v3.7.12"
    pullPolicy: Always
  service:
    annotations: {}
  resources: {}
